bases:
  - ./environments.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

helmDefaults:
  kubeContext: {{ .Environment.Values.kubeContext }}
  wait: false
  force: false

releases:
  - name: kenshoo-namespace
    chart: ./charts/namespace
    version: 0.1.0
    namespace: kube-system
    values:
      - ./values/{{ .Environment.Name }}/kenshoo-namespace.yaml