bases:
  - ./environments.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

helmDefaults:
  kubeContext: {{ .Environment.Values.kubeContext }}
  wait: false
  force: false

releases:
  - name: play-namespace
    chart: ./charts/namespace
    version: 0.1.0
    namespace: kube-system
    values:
      - ./values/{{ .Environment.Name }}/play-namespace.yaml
  - name: jenkins-secrets
    chart: ./charts/secrets
    namespace: jenkins
    values:
      - ./values/{{ .Environment.Name }}/jenkins-secrets.yaml
