bases:
  - ./environments.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: argocd
    url: https://argoproj.github.io/argo-helm

helmDefaults:
  kubeContext: {{ .Environment.Values.kubeContext }}
  wait: false
  force: false

releases:
  - name: netgod-namespace
    chart: ./charts/namespace
    version: 0.1.0
    namespace: kube-system
    values:
      - ./values/{{ .Environment.Name }}/netgod-namespace.yaml
  - name: argocd
    namespace: argocd
    chart: argocd/argo-cd
    version: 5.51.6
    needs:
      - minikube/kube-system/netgod-namespace
    values:
      - ./values/{{ .Environment.Name }}/argocd.yaml
      - ./secrets.yaml
  - name: jenkins
    chart: ./charts/jenkins
    version: 0.1.0
    namespace: jenkins
    needs:
      - minikube/kube-system/netgod-namespace
    values:
      - ./values/{{ .Environment.Name }}/netgod-jenkins.yaml
      - ./secrets.yaml

