### templates/repo-secret.yaml
{{- if and .Values.sharedSecrets.githubSshPrivateKey .Values.sharedSecrets.knownHosts }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-helmfiles
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-options: Skip
type: Opaque
stringData:
  type: git
  url: git@github.com:yudapinhas/helmfiles.git
  name: helmfiles
  sshPrivateKey: |
{{ .Values.sharedSecrets.githubSshPrivateKey | indent 4 }}
  known_hosts: |
{{ .Values.sharedSecrets.knownHosts | indent 4 }}
{{- end }}
