### root-app.yaml (app-of-apps)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yudapinhas/helmfiles.git
    targetRevision: {{ .Values.cluster.revision | default "HEAD" }}
    path: values/{{ .Values.cluster.name }}
  destination:
    namespace: argocd
    server: {{ .Values.cluster.apiServer | default "https://kubernetes.default.svc" }}
  syncPolicy: {}
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: ngrok-secret
    namespace: jenkins
    jsonPointers:
    - /data/authtoken
  - group: ""
    kind: Secret
    name: terraform-cloud-token
    namespace: jenkins
    jsonPointers:
    - /data/text
  - group: ""
    kind: Secret
    name: github-ssh-key
    namespace: jenkins
    jsonPointers:
    - /data/id_rsa
  - group: ""
    kind: Secret
    name: gcp-sa-json
    namespace: jenkins
    jsonPointers:
    - /data/data
