{{- range .Values.namespaces }}
{{- if .create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}