apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: kafka-to-sql-etl
spec:
  serviceAccountName: argo-workflows-sa
  entrypoint: main

  templates:
  - name: main
    steps:
    - - name: process-message
        template: kafka-to-sql-step
  - name: kafka-to-sql-step
    container:
      image: kafka-to-sql-consumer:latest
      imagePullPolicy: Never
      command: ["python", "consumer.py"]

      env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: kafka:9092
      - name: KAFKA_TOPIC
        value: etl_topic

      - name: KAFKA_SECURITY_PROTOCOL
        value: SASL_PLAINTEXT
      - name: KAFKA_SASL_MECHANISM
        value: PLAIN

      - name: KAFKA_SASL_USERNAME
        valueFrom:
          secretKeyRef:
            name: kafka-kafka
            key: client-users
      - name: KAFKA_SASL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kafka-kafka
            key: client-passwords

      - name: POSTGRES_HOST
        value: postgresql
      - name: POSTGRES_DB
        value: etldb
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql
            key: postgres-password

      - name: KAFKA_CLIENT_CONFIG
        value: /etc/kafka/client.properties

      volumeMounts:
      - name: kafka-client-config
        mountPath: /etc/kafka
        readOnly: true

    volumes:
    - name: kafka-client-config
      secret:
        secretName: kafka-kafka
        items:
        - key: client.properties
          path: client.properties