### kafka-to-sql-workflow.yaml
apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: kafka-to-sql-etl-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: process-message
        template: kafka-to-sql-step

  - name: kafka-to-sql-step
    container:
      image: kafka-to-sql-consumer:latest
      command: ["python"]
      args: ["consumer.py"]
      env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: kafka.kafka.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: etl_topic
      - name: POSTGRES_HOST
        value: postgresql.postgresql.svc.cluster.local
      - name: POSTGRES_DB
        value: etldb
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql
            key: postgresql-password
