### jenkins.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  project: default
  source:
    repoURL: git@github.com:yudapinhas/helmfiles.git
    targetRevision: HEAD
    path: charts/jenkins
    helm:
      valueFiles:
        - ../../values/netgod-play-cluster/netgod-jenkins.yaml
        - ../../secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
    ignoreDifferences:
    - group: ""
      kind: Secret
      name: ngrok-secret
      namespace: jenkins
      jsonPointers:
      - /data/authtoken
    - group: ""
      kind: Secret
      name: terraform-cloud-token
      namespace: jenkins
      jsonPointers:
      - /data/text
    - group: ""
      kind: Secret
      name: github-ssh-key
      namespace: jenkins
      jsonPointers:
      - /data/id_rsa
    - group: ""
      kind: Secret
      name: gcp-sa-json
      namespace: jenkins
      jsonPointers:
      - /data/data
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
