### argo-pipelines/base/manifests/argo-workflow-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-binding
  namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sa
    namespace: argo-workflows