apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.controller.image }}:{{ .Values.controller.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: JENKINS_ADMIN_ID
              value: "{{ .Values.controller.adminUser }}"
            - name: JENKINS_ADMIN_PASSWORD
              value: "{{ .Values.controller.adminPassword }}"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}