apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-dsl-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  seedJob.groovy: |
{{ .Files.Get "jenkins-dsl/seedJob.groovy" | indent 4 }}
  repos.groovy: |-
{{ .Files.Get "jenkins-dsl/repos.groovy" | indent 4 }}