---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
  namespace: jenkins
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Skip
type: Opaque
data:
  id_rsa: {{ .Values.controller.ssh.privateKey | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-known-hosts
  namespace: jenkins
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Skip
data:
  known_hosts: {{ .Values.controller.ssh.knownHosts | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngrok-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Skip
type: Opaque
data:
  authtoken: {{ .Values.ngrok.authtoken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: terraform-cloud-token
  namespace: jenkins
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
    jenkins.io/credentials-type: secretText
    jenkins.io/credentials-scope: GLOBAL
  annotations:
    argocd.argoproj.io/sync-options: Skip
stringData:
  text: {{ .Values.terraformCloud.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-sa-json 
  namespace: jenkins
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
    jenkins.io/credentials-type: secretFile
    jenkins.io/credentials-scope: GLOBAL
  annotations:
    argocd.argoproj.io/sync-options: Skip
type: Opaque
data:
  filename: Y3JlZGVudGlhbHMuanNvbg==
  data: |-
    {{ .Values.gcp.serviceAccountKey | indent 4 }}