---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
  namespace: jenkins
type: Opaque
data:
  id_rsa: {{ .Values.controller.ssh.privateKey | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-known-hosts
  namespace: jenkins
data:
  known_hosts: {{ .Values.controller.ssh.knownHosts | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngrok-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  authtoken: {{ .Values.ngrok.authtoken | b64enc | quote }}