---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: {{ .Values.controller.service.type | default "ClusterIP" }}
  selector:
    app: jenkins
  ports:
    - port: {{ .Values.controller.service.port | default 8080 }}
      targetPort: 8080
        {{- if eq .Values.controller.service.type "NodePort" }}
      nodePort: {{ .Values.controller.service.nodePort | default 30080 }}
        {{- end }}